import Head from 'next/head'
import GameLogic from '@/gameLogic'
import { useEffect, useRef } from 'react'

export default function Home() {
  const gameLogic = useRef<GameLogic | null>(null);
  useEffect(() => {
    gameLogic.current = new GameLogic();

    return () => gameLogic.current?.dispose();
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative'>
        <canvas id='canvas' className=' w-full h-full'></canvas>
        <div className='absolute select-none pointer-events-none top-5 bg-white rounded-xl px-10 py-2 right-5'>
          <span className='pointer-events-none'>Score: </span>
          <span className='pointer-events-none' id='gameScore'>0</span>
        </div>

        <div id='gameOverWrapper' className='absolute select-none hidden space-y-5 bg-white py-5 px-20 rounded-2xl top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 flex-col items-center'>
          <span className=' text-2xl font-bold'>Game Over</span>
          <span id='gameOverScore'>Score: 100</span>
          <button onClick={() => gameLogic.current?.restartGame()} className='bg-slate-600 border text-white py-2 px-5 rounded-xl transition-all duration-500 hover:bg-transparent hover:text-black hover:border-slate-600'>Restart Game</button>
        </div>
      </main>
    </>
  )
}
